name = "BioStructures"
uuid = "de9282ab-8554-53be-b2d6-f6c222edabfc"
authors = ["Joe G Greener <jgreener@hotmail.co.uk>"]
version = "4.7.0"

[deps]
BioGenerics = "47718e42-2ac5-11e9-14af-e5595289c2ea"
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
BioAlignments = "00701ae9-d1dc-5365-b64a-a3a3ebf5695e"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
DSSP_jll = "74334e00-59ce-546d-b517-81f3b7e1d491"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MMTF = "259c3a9c-12c3-507f-b21f-68ecc40fcda4"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
STRIDE_jll = "850473c1-9ef0-5df9-a957-757f4cde8b8b"

[extensions]
BioStructuresBioAlignmentsExt = ["BioSequences", "BioAlignments"]
BioStructuresBioSequencesExt = "BioSequences"
BioStructuresDSSPExt = "DSSP_jll"
BioStructuresDataFramesExt = "DataFrames"
BioStructuresGraphsExt = ["Graphs", "MetaGraphs"]
BioStructuresMMTFExt = "MMTF"
BioStructuresSTRIDEExt = "STRIDE_jll"

[compat]
BioAlignments = "3"
BioGenerics = "0.1"
BioSequences = "3"
BioSymbols = "5"
CodecZlib = "0.7"
DSSP_jll = "4.4"
DataFrames = "1"
Downloads = "1"
Format = "1.3"
Graphs = "1"
LinearAlgebra = "1.9"
MMTF = "1"
MetaGraphs = "0.7, 0.8"
PrecompileTools = "1"
RecipesBase = "1"
STRIDE_jll = "1"
Statistics = "1.9"
julia = "1.9"
